---
title: "Foodproduction on Countries"
author: "Yuhan Wu"
date: "A/A4/A0AA"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(dplyr)
library(plotly)
library(png)
library(ggplot2)
library(ggthemes)
```

```{r, echo=FALSE}
barleyA <- read.csv("barley-production.csv")
cassavaA <- read.csv("cassava-production.csv")
cerealA <- read.csv("cereal-production.csv")
maizeA <- read.csv("maize-production.csv")
potatoA <- read.csv("potato-production.csv")
riceA <- read.csv("rice-production.csv")
ryeA <- read.csv("rye-production.csv")
sweetpotatoA <- read.csv("sweet-potato-production.csv")
wheatA <- read.csv("wheat-production.csv")
yamsA <- read.csv("yams-production.csv")

appleA <- read.csv("apple-production.csv")
avocadoA <- read.csv("avocado-production.csv")
bananaA <- read.csv("banana-production.csv")
beanA <- read.csv("bean-production.csv")
cashewA <- read.csv("cashew-nut-production.csv")
grapesA <- read.csv("grapes-production.csv")
orangeA <- read.csv("orange-production.csv")
peaA <- read.csv("pea-production.csv")
soybeanA <- read.csv("soybean-production.csv")
tomatoA <- read.csv("tomato-production.csv")
```

```{r,echo=FALSE}
names(barleyA)[4] <- 'Production'
names(cassavaA)[4] <- 'Production'
names(cerealA)[4] <- 'Production'
names(maizeA)[4] <- 'Production'
names(potatoA)[4] <- 'Production'
names(riceA)[4] <- 'Production'
names(ryeA)[4] <- 'Production'
names(sweetpotatoA)[4] <- 'Production'
names(wheatA)[4] <- 'Production'
names(yamsA)[4] <- 'Production'

names(appleA)[4] <- 'Production'
names(avocadoA)[4] <- 'Production'
names(bananaA)[4] <- 'Production'
names(beanA)[4] <- 'Production'
names(cashewA)[4] <- 'Production'
names(grapesA)[4] <- 'Production'
names(orangeA)[4] <- 'Production'
names(peaA)[4] <- 'Production'
names(soybeanA)[4] <- 'Production'
names(tomatoA)[4] <- 'Production'
  
```

```{r, echo=FALSE}
countries_prod <- bind_rows(barleyA,cassavaA,cerealA, cerealA, maizeA, potatoA, riceA, ryeA, sweetpotatoA, wheatA, yamsA,appleA, avocadoA, bananaA, beanA, cashewA, grapesA, orangeA, peaA, soybeanA, tomatoA)

Northern_America <- countries_prod %>%
  filter(Entity == "Northern America") %>%
  select(Year,Production)%>%
  group_by(Year) %>%
  summarise(Production = sum(Production)/1000000000, .groups = 'drop')%>%
  mutate(Continent = "Northern America")

Africa <- countries_prod %>%
  filter(Entity == "Africa") %>%
  select(Year,Production)%>%
  group_by(Year) %>%
  summarise(Production = sum(Production)/1000000000, .groups = 'drop')%>%
  mutate(Continent = "Africa")

Europe <- countries_prod %>%
  filter(Entity == "Europe") %>%
  select(Year,Production)%>%
  group_by(Year) %>%
  summarise(Production = sum(Production)/1000000000, .groups = 'drop')%>%
  mutate(Continent = "Europe")

Asia <- countries_prod %>%
  filter(Entity == "Asia") %>%
  select(Year,Production)%>%
  group_by(Year) %>%
  summarise(Production = sum(Production)/1000000000, .groups = 'drop')%>%
  mutate(Continent = "Asia")

South_America <- countries_prod %>%
  filter(Entity == "South America") %>%
  select(Year,Production)%>%
  group_by(Year) %>%
  summarise(Production = sum(Production)/1000000000, .groups = 'drop')%>%
  mutate(Continent = "South America")

Central_America <- countries_prod %>%
  filter(Entity == "Central America") %>%
  select(Year,Production)%>%
  group_by(Year) %>%
  summarise(Production = sum(Production)/1000000000, .groups = 'drop')%>%
  mutate(Continent = "Central America")

Oceania <- countries_prod %>%
  filter(Entity == "Oceania") %>%
  select(Year,Production)%>%
  group_by(Year) %>%
  summarise(Production = sum(Production)/1000000000, .groups = 'drop')%>%
  mutate(Continent = "Oceania")

bind_rows(Northern_America,Africa,Europe,Asia,South_America,Central_America,Oceania) %>%
  ggplot(aes(x=Year, y = Production, color = Continent))+
  geom_line()+
  scale_x_continuous( breaks = c(1960, 1970, 1980, 1990, 2000, 2010, 2020))+
  labs(title = "Food Production For Different Continents", subtitle = "Asia take the lead in food production",y = "Production (Billion)")




```






