---
title: "Food Production and Population"
author: "NNHS Modeling"
date: "2/22/2022"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(dplyr)
library(plotly)
library(png)
library(ggplot2)
library(ggthemes)

```

```{r, echo=FALSE, warning=FALSE}
worldpop <- read.csv("Worldpop.csv")

worldpop2 <- worldpop %>%
  group_by(Year) %>%
  summarise(Value = Value/1000000000)

```


```{r, echo=FALSE, warning=FALSE}
barley <- read.csv("barley-production.csv")
cassava <- read.csv("cassava-production.csv")
cereal <- read.csv("cereal-production.csv")
maize <- read.csv("maize-production.csv")
potato <- read.csv("potato-production.csv")
rice <- read.csv("rice-production.csv")
rye <- read.csv("rye-production.csv")
sweetpotato <- read.csv("sweet-potato-production.csv")
wheat <- read.csv("wheat-production.csv")
yams <- read.csv("yams-production.csv")

apple <- read.csv("apple-production.csv")
avocado <- read.csv("avocado-production.csv")
banana <- read.csv("banana-production.csv")
bean <- read.csv("bean-production.csv")
cashew <- read.csv("cashew-nut-production.csv")
grapes <- read.csv("grapes-production.csv")
orange <- read.csv("orange-production.csv")
pea <- read.csv("pea-production.csv")
soybean <- read.csv("soybean-production.csv")
tomato <- read.csv("tomato-production.csv")

```


```{r, echo=FALSE, warning=FALSE}
names(barley)[4] <- 'Production'
names(cassava)[4] <- 'Production'
names(cereal)[4] <- 'Production'
names(maize)[4] <- 'Production'
names(potato)[4] <- 'Production'
names(rice)[4] <- 'Production'
names(rye)[4] <- 'Production'
names(sweetpotato)[4] <- 'Production'
names(wheat)[4] <- 'Production'
names(yams)[4] <- 'Production'

names(apple)[4] <- 'Production'
names(avocado)[4] <- 'Production'
names(banana)[4] <- 'Production'
names(bean)[4] <- 'Production'
names(cashew)[4] <- 'Production'
names(grapes)[4] <- 'Production'
names(orange)[4] <- 'Production'
names(pea)[4] <- 'Production'
names(soybean)[4] <- 'Production'
names(tomato)[4] <- 'Production'
```

```{r, echo=FALSE, warning=FALSE}
barley2 <- barley %>%
  filter(Entity == "World") %>%
  select(Entity, Year, Production)

cassava2 <- cassava %>%
  filter(Entity == "World") %>%
  select(Entity, Year, Production)

cereal2 <- cereal %>%
  filter(Entity == "World") %>%
  select(Entity, Year, Production)

maize2 <- maize %>%
  filter(Entity == "World") %>%
  select(Entity, Year, Production)

potato2 <- potato %>%
  filter(Entity == "World") %>%
  select(Entity, Year, Production)

rice2 <- rice %>%
  filter(Entity == "World") %>%
  select(Entity, Year, Production)

rye2 <- rye %>%
  filter(Entity == "World") %>%
  select(Entity, Year, Production)

sweetpotato2 <- sweetpotato %>%
  filter(Entity == "World") %>%
  select(Entity, Year, Production)

wheat2 <- wheat %>%
  filter(Entity == "World") %>%
  select(Entity, Year, Production)

yams2 <- yams %>%
  filter(Entity == "World") %>%
  select(Entity, Year, Production)


apple2 <- apple %>%
  filter(Entity == "World") %>%
  select(Entity, Year, Production)

avocado2 <- avocado %>%
  filter(Entity == "World") %>%
  select(Entity, Year, Production)

banana2 <- banana %>%
  filter(Entity == "World") %>%
  select(Entity, Year, Production)

bean2 <- bean %>%
  filter(Entity == "World") %>%
  select(Entity, Year, Production)

cashew2 <- cashew %>%
  filter(Entity == "World") %>%
  select(Entity, Year, Production)

grapes2 <- grapes %>%
  filter(Entity == "World") %>%
  select(Entity, Year, Production)

orange2 <- orange %>%
  filter(Entity == "World") %>%
  select(Entity, Year, Production)

pea2 <- pea %>%
  filter(Entity == "World") %>%
  select(Entity, Year, Production)

soybean2 <- soybean %>%
  filter(Entity == "World") %>%
  select(Entity, Year, Production)

tomato2 <- tomato %>%
  filter(Entity == "World") %>%
  select(Entity, Year, Production)





```




```{r, echo=FALSE, warning=FALSE}
Production_combine <- bind_rows(barley2,cassava2,cereal2, cereal2, maize2, potato2, rice2, rye2, sweetpotato2, wheat2, yams2,apple2, avocado2, banana2, bean2, cashew2, grapes2, orange2, pea2, soybean2, tomato2) %>%
  group_by(Year) %>%
  summarise(Value = sum(Production)/1000000000)%>%
  mutate(Group ="Food Production")

worldpop3 <- worldpop2 %>%
  mutate(Group ="Population")

data_combine <- bind_rows(Production_combine, worldpop3)

data_final <- data_combine%>%
  group_by(Year) %>%
  summarise(Value,Group,.groups = 'drop')

```

```{r, echo=FALSE, warning=FALSE}
data_plotly <- data_final %>%
  ggplot(mapping = aes(x = Year, y = Value, color = Group))+
  geom_point()+
  geom_smooth(method=lm, se=FALSE, formula = y~x)+
  scale_x_continuous( breaks = c(1960, 1970, 1980, 1990, 2000, 2010, 2020))+
  labs(title="Food Production vs Population (In Billion)", subtitle = "Food production have a higher growth rate than population",x="Time",y="Values (Billion)") +
  theme_fivethirtyeight()

ggplotly(data_plotly)






```



# Population Growth Rate




```{r, echo=FALSE, warning=FALSE}
pop_growth <- worldpop3%>%
  arrange(Year) %>%
  mutate(Diff_year = Year - lag(Year),  # Difference in time (just in case there are gaps)
         Diff_growth = Value - lag(Value), # Difference in value between years
         Rate_percent = (Diff_growth / Diff_year)/lag(Value) * 100) %>%
  drop_na()

food_growth <- Production_combine %>%
  arrange(Year) %>%
  mutate(Diff_year = Year - lag(Year),  # Difference in time (just in case there are gaps)
         Diff_growth = Value - lag(Value), # Difference in value between years
         Rate_percent = (Diff_growth / Diff_year)/lag(Value) * 100) %>%
  drop_na()

pop_growth_final <- pop_growth%>%
  ggplot(mapping = aes(x= Year, y = Rate_percent)) +
  geom_line()+
  scale_x_continuous(limits=c(1962,2018),breaks = c(1960, 1970, 1980, 1990, 2000, 2010, 2020))+
  labs(title = "Population Growth Rate (Billion)")

food_growth_final <- food_growth%>%
  ggplot(mapping = aes(x= Year, y = Rate_percent)) +
  geom_line()+
  scale_x_continuous(limits=c(1962,2018), breaks = c(1960, 1970, 1980, 1990, 2000, 2010, 2020))+
  labs(title = "Food Production Growth Rate (Billion)")

pop_growth_select <- pop_growth %>%
  mutate(Group ="Population") %>%
  select(Year,Rate_percent,Group)

food_growth_select <- food_growth %>%
  mutate(Group ="Food") %>%
  select(Year,Rate_percent,Group)

growth_data_combine <- bind_rows(pop_growth_select, food_growth_select)

growth_data_final <- growth_data_combine%>%
  group_by(Year) %>%
  summarise(Rate_percent,Group,.groups = 'drop')

growth_data_plotly <- growth_data_final %>%
  ggplot(mapping = aes(x = Year, y = Rate_percent, color = Group))+
  geom_point()+
  geom_smooth(method = lm, se= FALSE,formula = y~x)+
  scale_x_continuous( breaks = c(1960, 1970, 1980, 1990, 2000, 2010, 2020))+
  labs(title="Food Production vs Population (In Billion)") +
  theme_fivethirtyeight()

ggplotly(growth_data_plotly)
ggplotly(pop_growth_final)
ggplotly(food_growth_final)

```



